name: Java CI with Gradle

on:
  push:
    branches: [ "remapped" ]
  pull_request:
    branches: [ "remapped" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle Wrapper
      run: ./gradlew build
    - name: artifact
      uses: actions/upload-artifact@v3   
      with:
        name: HMCWraps
        path: run/plugins/HMCWraps.jar
